import { CHATROOM_TYPE, MAJOR_TYPE } from "@common/constants";

export const defaultFriendsList = [
  {
    id: 0,
    img: "/img/nightview.jpg",
    name: "최윤서",
    message: "디자인 화이팅~!!",
    majorIn: MAJOR_TYPE.DESIGNER,
    phoneNumber: "+82)10-2356-2349",
    phoneLink: "",
    email: "yunseo@naver.com",
    emailLink: "",
    behanceLink: "https://www.behance.net/",
    instagramLink: "https://www.instagram.com/",
    githubLink: "https://github.com/",
    group: {
      id: 0,
      name: "기업적디자인스튜디오(1)",
      state: CHATROOM_TYPE.MAIN,
    },
  },
  {
    id: 1,
    img: "/img/wolf.jpg",
    name: "김다인",
    message: "상태메세지",
    majorIn: MAJOR_TYPE.DESIGNER,
    phoneNumber: "+82)10-4938-8392",
    phoneLink: "",
    email: "dain@naver.com",
    emailLink: "",
    behanceLink: "https://www.behance.net/",
    instagramLink: "https://www.instagram.com/",
    githubLink: "https://github.com/",
    group: {
      id: 2,
      name: "2022-1 사이드프로젝트",
      state: CHATROOM_TYPE.SUB,
    },
  },
  {
    id: 2,
    img: "/img/tottenham.jpg",
    name: "김진호",
    message: "프론트 화이팅~!!",
    majorIn: MAJOR_TYPE.FRONTEND,
    phoneNumber: "+82)10-0237-2789",
    phoneLink: "",
    email: "jingo@naver.com",
    emailLink: "",
    behanceLink: "https://www.behance.net/",
    instagramLink: "https://www.instagram.com/",
    githubLink: "https://github.com/",
    group: {
      id: 0,
      name: "기업적디자인스튜디오(1)",
      state: CHATROOM_TYPE.MAIN,
    },
  },
  {
    id: 3,
    img: "/img/beer.jpg",
    name: "김지원",
    message: "상태메세지",
    majorIn: MAJOR_TYPE.FRONTEND,
    phoneNumber: "+82)10-9052-0152",
    phoneLink: "",
    email: "jiwon@naver.com",
    emailLink: "",
    behanceLink: "https://www.behance.net/",
    instagramLink: "https://www.instagram.com/",
    githubLink: "https://github.com/",
    group: {
      id: 1,
      name: "2022-2 사이드프로젝트",
      state: CHATROOM_TYPE.SUB,
    },
  },
  {
    id: 3,
    img: "/img/default.jpg",
    name: "전윤수",
    message: "세오스 화이팅!",
    majorIn: MAJOR_TYPE.DESIGNER,
    phoneNumber: "+82)10-8594-0626",
    phoneLink: "",
    email: "yunsu@naver.com",
    emailLink: "",
    behanceLink: "https://www.behance.net/",
    instagramLink: "https://www.instagram.com/",
    githubLink: "https://github.com/",
    group: {
      id: 0,
      name: "CEOS 18기 펫뷸러스",
      state: CHATROOM_TYPE.MAIN,
    },
  },
];
